//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTechnologiesMVCADO.CodeTechWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamNature", Namespace="http://schemas.datacontract.org/2004/07/CodeTechnologiesWCF.HelperClass.Exams")]
    [System.SerializableAttribute()]
    public partial class ExamNature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamsType", Namespace="http://schemas.datacontract.org/2004/07/CodeTechnologiesWCF.HelperClass.Exams")]
    [System.SerializableAttribute()]
    public partial class ExamsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamType {
            get {
                return this.ExamTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTypeField, value) != true)) {
                    this.ExamTypeField = value;
                    this.RaisePropertyChanged("ExamType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamCodes", Namespace="http://schemas.datacontract.org/2004/07/CodeTechnologiesWCF.HelperClass.Exams")]
    [System.SerializableAttribute()]
    public partial class ExamCodes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamCode {
            get {
                return this.ExamCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamCodeField, value) != true)) {
                    this.ExamCodeField = value;
                    this.RaisePropertyChanged("ExamCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamType {
            get {
                return this.ExamTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTypeField, value) != true)) {
                    this.ExamTypeField = value;
                    this.RaisePropertyChanged("ExamType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcademyModel", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.HelperClass")]
    [System.SerializableAttribute()]
    public partial class AcademyModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POCName {
            get {
                return this.POCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.POCNameField, value) != true)) {
                    this.POCNameField = value;
                    this.RaisePropertyChanged("POCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrometricCandidate", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.HelperClass")]
    [System.SerializableAttribute()]
    public partial class PrometricCandidate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamNatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoucherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttemptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExamDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstituteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AbroadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ExamNature {
            get {
                return this.ExamNatureField;
            }
            set {
                if ((this.ExamNatureField.Equals(value) != true)) {
                    this.ExamNatureField = value;
                    this.RaisePropertyChanged("ExamNature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ExamId {
            get {
                return this.ExamIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamIdField, value) != true)) {
                    this.ExamIdField = value;
                    this.RaisePropertyChanged("ExamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string VoucherId {
            get {
                return this.VoucherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherIdField, value) != true)) {
                    this.VoucherIdField = value;
                    this.RaisePropertyChanged("VoucherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CandidateId {
            get {
                return this.CandidateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateIdField, value) != true)) {
                    this.CandidateIdField = value;
                    this.RaisePropertyChanged("CandidateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ExamStatus {
            get {
                return this.ExamStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamStatusField, value) != true)) {
                    this.ExamStatusField = value;
                    this.RaisePropertyChanged("ExamStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Attempts {
            get {
                return this.AttemptsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttemptsField, value) != true)) {
                    this.AttemptsField = value;
                    this.RaisePropertyChanged("Attempts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> ExamDate {
            get {
                return this.ExamDateField;
            }
            set {
                if ((this.ExamDateField.Equals(value) != true)) {
                    this.ExamDateField = value;
                    this.RaisePropertyChanged("ExamDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int InstituteId {
            get {
                return this.InstituteIdField;
            }
            set {
                if ((this.InstituteIdField.Equals(value) != true)) {
                    this.InstituteIdField = value;
                    this.RaisePropertyChanged("InstituteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool Abroad {
            get {
                return this.AbroadField;
            }
            set {
                if ((this.AbroadField.Equals(value) != true)) {
                    this.AbroadField = value;
                    this.RaisePropertyChanged("Abroad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileData", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class FileData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BufferDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilePositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BufferData {
            get {
                return this.BufferDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BufferDataField, value) != true)) {
                    this.BufferDataField = value;
                    this.RaisePropertyChanged("BufferData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilePosition {
            get {
                return this.FilePositionField;
            }
            set {
                if ((this.FilePositionField.Equals(value) != true)) {
                    this.FilePositionField = value;
                    this.RaisePropertyChanged("FilePosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prometric", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.HelperClass")]
    [System.SerializableAttribute()]
    public partial class Prometric : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int POCPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POCEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsHiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerExamProfitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TCAAdminIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteOwnerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string POCName {
            get {
                return this.POCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.POCNameField, value) != true)) {
                    this.POCNameField = value;
                    this.RaisePropertyChanged("POCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int POCPhone {
            get {
                return this.POCPhoneField;
            }
            set {
                if ((this.POCPhoneField.Equals(value) != true)) {
                    this.POCPhoneField = value;
                    this.RaisePropertyChanged("POCPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string POCEmail {
            get {
                return this.POCEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.POCEmailField, value) != true)) {
                    this.POCEmailField = value;
                    this.RaisePropertyChanged("POCEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string SiteAddress {
            get {
                return this.SiteAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteAddressField, value) != true)) {
                    this.SiteAddressField = value;
                    this.RaisePropertyChanged("SiteAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<bool> IsHired {
            get {
                return this.IsHiredField;
            }
            set {
                if ((this.IsHiredField.Equals(value) != true)) {
                    this.IsHiredField = value;
                    this.RaisePropertyChanged("IsHired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string PerExamProfit {
            get {
                return this.PerExamProfitField;
            }
            set {
                if ((object.ReferenceEquals(this.PerExamProfitField, value) != true)) {
                    this.PerExamProfitField = value;
                    this.RaisePropertyChanged("PerExamProfit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int TCAAdminId {
            get {
                return this.TCAAdminIdField;
            }
            set {
                if ((this.TCAAdminIdField.Equals(value) != true)) {
                    this.TCAAdminIdField = value;
                    this.RaisePropertyChanged("TCAAdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string SiteOwnerName {
            get {
                return this.SiteOwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteOwnerNameField, value) != true)) {
                    this.SiteOwnerNameField = value;
                    this.RaisePropertyChanged("SiteOwnerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrometricPromotions", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.HelperClass")]
    [System.SerializableAttribute()]
    public partial class PrometricPromotions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MarginGainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MarginMissField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> MarginGain {
            get {
                return this.MarginGainField;
            }
            set {
                if ((this.MarginGainField.Equals(value) != true)) {
                    this.MarginGainField = value;
                    this.RaisePropertyChanged("MarginGain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> MarginMiss {
            get {
                return this.MarginMissField;
            }
            set {
                if ((this.MarginMissField.Equals(value) != true)) {
                    this.MarginMissField = value;
                    this.RaisePropertyChanged("MarginMiss");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Institute", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.HelperClass")]
    [System.SerializableAttribute()]
    public partial class Institute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreditAllowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreditRemainingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POCName {
            get {
                return this.POCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.POCNameField, value) != true)) {
                    this.POCNameField = value;
                    this.RaisePropertyChanged("POCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> CreditAllowed {
            get {
                return this.CreditAllowedField;
            }
            set {
                if ((this.CreditAllowedField.Equals(value) != true)) {
                    this.CreditAllowedField = value;
                    this.RaisePropertyChanged("CreditAllowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> CreditRemaining {
            get {
                return this.CreditRemainingField;
            }
            set {
                if ((this.CreditRemainingField.Equals(value) != true)) {
                    this.CreditRemainingField = value;
                    this.RaisePropertyChanged("CreditRemaining");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeTechWCF.ICodeTechnologiesServices")]
    public interface ICodeTechnologiesServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExams/GetAllExamNature", ReplyAction="http://tempuri.org/IExams/GetAllExamNatureResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamNature> GetAllExamNature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExams/GetAllExamNature", ReplyAction="http://tempuri.org/IExams/GetAllExamNatureResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamNature>> GetAllExamNatureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExams/GetAllExamTypes", ReplyAction="http://tempuri.org/IExams/GetAllExamTypesResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamsType> GetAllExamTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExams/GetAllExamTypes", ReplyAction="http://tempuri.org/IExams/GetAllExamTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamsType>> GetAllExamTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExams/GetAllExamCodes", ReplyAction="http://tempuri.org/IExams/GetAllExamCodesResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamCodes> GetAllExamCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExams/GetAllExamCodes", ReplyAction="http://tempuri.org/IExams/GetAllExamCodesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamCodes>> GetAllExamCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/GetAllAcademies", ReplyAction="http://tempuri.org/IAcademy/GetAllAcademiesResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel> GetAllAcademies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/GetAllAcademies", ReplyAction="http://tempuri.org/IAcademy/GetAllAcademiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel>> GetAllAcademiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/AdddAcademy", ReplyAction="http://tempuri.org/IAcademy/AdddAcademyResponse")]
        void AdddAcademy(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/AdddAcademy", ReplyAction="http://tempuri.org/IAcademy/AdddAcademyResponse")]
        System.Threading.Tasks.Task AdddAcademyAsync(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/getAcademy", ReplyAction="http://tempuri.org/IAcademy/getAcademyResponse")]
        CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel getAcademy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/getAcademy", ReplyAction="http://tempuri.org/IAcademy/getAcademyResponse")]
        System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel> getAcademyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/UpdateAcademy", ReplyAction="http://tempuri.org/IAcademy/UpdateAcademyResponse")]
        void UpdateAcademy(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/UpdateAcademy", ReplyAction="http://tempuri.org/IAcademy/UpdateAcademyResponse")]
        System.Threading.Tasks.Task UpdateAcademyAsync(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/DeleteAcademy", ReplyAction="http://tempuri.org/IAcademy/DeleteAcademyResponse")]
        void DeleteAcademy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademy/DeleteAcademy", ReplyAction="http://tempuri.org/IAcademy/DeleteAcademyResponse")]
        System.Threading.Tasks.Task DeleteAcademyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricCandidate/GetAllPrometricCandidates", ReplyAction="http://tempuri.org/IPrometricCandidate/GetAllPrometricCandidatesResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate> GetAllPrometricCandidates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricCandidate/GetAllPrometricCandidates", ReplyAction="http://tempuri.org/IPrometricCandidate/GetAllPrometricCandidatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate>> GetAllPrometricCandidatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricCandidate/BulkUploadPrometricCandidates", ReplyAction="http://tempuri.org/IPrometricCandidate/BulkUploadPrometricCandidatesResponse")]
        void BulkUploadPrometricCandidates(CodeTechnologiesMVCADO.CodeTechWCF.FileData inputexcel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricCandidate/BulkUploadPrometricCandidates", ReplyAction="http://tempuri.org/IPrometricCandidate/BulkUploadPrometricCandidatesResponse")]
        System.Threading.Tasks.Task BulkUploadPrometricCandidatesAsync(CodeTechnologiesMVCADO.CodeTechWCF.FileData inputexcel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/GetAllPrometrics", ReplyAction="http://tempuri.org/IPrometric/GetAllPrometricsResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Prometric> GetAllPrometrics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/GetAllPrometrics", ReplyAction="http://tempuri.org/IPrometric/GetAllPrometricsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Prometric>> GetAllPrometricsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/AddPrometric", ReplyAction="http://tempuri.org/IPrometric/AddPrometricResponse")]
        void AddPrometric(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/AddPrometric", ReplyAction="http://tempuri.org/IPrometric/AddPrometricResponse")]
        System.Threading.Tasks.Task AddPrometricAsync(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/getPrometric", ReplyAction="http://tempuri.org/IPrometric/getPrometricResponse")]
        CodeTechnologiesMVCADO.CodeTechWCF.Prometric getPrometric(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/getPrometric", ReplyAction="http://tempuri.org/IPrometric/getPrometricResponse")]
        System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.Prometric> getPrometricAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/UpdatePrometric", ReplyAction="http://tempuri.org/IPrometric/UpdatePrometricResponse")]
        void UpdatePrometric(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/UpdatePrometric", ReplyAction="http://tempuri.org/IPrometric/UpdatePrometricResponse")]
        System.Threading.Tasks.Task UpdatePrometricAsync(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/DeletePrometric", ReplyAction="http://tempuri.org/IPrometric/DeletePrometricResponse")]
        void DeletePrometric(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometric/DeletePrometric", ReplyAction="http://tempuri.org/IPrometric/DeletePrometricResponse")]
        System.Threading.Tasks.Task DeletePrometricAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/getAllPrometricPromotions", ReplyAction="http://tempuri.org/IPrometricPromotions/getAllPrometricPromotionsResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions> getAllPrometricPromotions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/getAllPrometricPromotions", ReplyAction="http://tempuri.org/IPrometricPromotions/getAllPrometricPromotionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions>> getAllPrometricPromotionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/getPrometricPromotionWithSiteId", ReplyAction="http://tempuri.org/IPrometricPromotions/getPrometricPromotionWithSiteIdResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions> getPrometricPromotionWithSiteId(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/getPrometricPromotionWithSiteId", ReplyAction="http://tempuri.org/IPrometricPromotions/getPrometricPromotionWithSiteIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions>> getPrometricPromotionWithSiteIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/AddPrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/AddPrometricPromotionResponse")]
        void AddPrometricPromotion(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/AddPrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/AddPrometricPromotionResponse")]
        System.Threading.Tasks.Task AddPrometricPromotionAsync(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/getPrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/getPrometricPromotionResponse")]
        CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions getPrometricPromotion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/getPrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/getPrometricPromotionResponse")]
        System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions> getPrometricPromotionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/UpdatePrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/UpdatePrometricPromotionResponse")]
        void UpdatePrometricPromotion(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/UpdatePrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/UpdatePrometricPromotionResponse")]
        System.Threading.Tasks.Task UpdatePrometricPromotionAsync(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/DeletePrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/DeletePrometricPromotionResponse")]
        void DeletePrometricPromotion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrometricPromotions/DeletePrometricPromotion", ReplyAction="http://tempuri.org/IPrometricPromotions/DeletePrometricPromotionResponse")]
        System.Threading.Tasks.Task DeletePrometricPromotionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/GetAllInstitutes", ReplyAction="http://tempuri.org/IInstitute/GetAllInstitutesResponse")]
        System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Institute> GetAllInstitutes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/GetAllInstitutes", ReplyAction="http://tempuri.org/IInstitute/GetAllInstitutesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Institute>> GetAllInstitutesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/AddInstitute", ReplyAction="http://tempuri.org/IInstitute/AddInstituteResponse")]
        void AddInstitute(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/AddInstitute", ReplyAction="http://tempuri.org/IInstitute/AddInstituteResponse")]
        System.Threading.Tasks.Task AddInstituteAsync(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/getInstitute", ReplyAction="http://tempuri.org/IInstitute/getInstituteResponse")]
        CodeTechnologiesMVCADO.CodeTechWCF.Institute getInstitute(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/getInstitute", ReplyAction="http://tempuri.org/IInstitute/getInstituteResponse")]
        System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.Institute> getInstituteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/UpdateInstitute", ReplyAction="http://tempuri.org/IInstitute/UpdateInstituteResponse")]
        void UpdateInstitute(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/UpdateInstitute", ReplyAction="http://tempuri.org/IInstitute/UpdateInstituteResponse")]
        System.Threading.Tasks.Task UpdateInstituteAsync(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/DeleteInstitute", ReplyAction="http://tempuri.org/IInstitute/DeleteInstituteResponse")]
        void DeleteInstitute(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstitute/DeleteInstitute", ReplyAction="http://tempuri.org/IInstitute/DeleteInstituteResponse")]
        System.Threading.Tasks.Task DeleteInstituteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeTechnologiesServicesChannel : CodeTechnologiesMVCADO.CodeTechWCF.ICodeTechnologiesServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeTechnologiesServicesClient : System.ServiceModel.ClientBase<CodeTechnologiesMVCADO.CodeTechWCF.ICodeTechnologiesServices>, CodeTechnologiesMVCADO.CodeTechWCF.ICodeTechnologiesServices {
        
        public CodeTechnologiesServicesClient() {
        }
        
        public CodeTechnologiesServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeTechnologiesServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeTechnologiesServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeTechnologiesServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamNature> GetAllExamNature() {
            return base.Channel.GetAllExamNature();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamNature>> GetAllExamNatureAsync() {
            return base.Channel.GetAllExamNatureAsync();
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamsType> GetAllExamTypes() {
            return base.Channel.GetAllExamTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamsType>> GetAllExamTypesAsync() {
            return base.Channel.GetAllExamTypesAsync();
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamCodes> GetAllExamCodes() {
            return base.Channel.GetAllExamCodes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.ExamCodes>> GetAllExamCodesAsync() {
            return base.Channel.GetAllExamCodesAsync();
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel> GetAllAcademies() {
            return base.Channel.GetAllAcademies();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel>> GetAllAcademiesAsync() {
            return base.Channel.GetAllAcademiesAsync();
        }
        
        public void AdddAcademy(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj) {
            base.Channel.AdddAcademy(academyObj);
        }
        
        public System.Threading.Tasks.Task AdddAcademyAsync(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj) {
            return base.Channel.AdddAcademyAsync(academyObj);
        }
        
        public CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel getAcademy(int id) {
            return base.Channel.getAcademy(id);
        }
        
        public System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel> getAcademyAsync(int id) {
            return base.Channel.getAcademyAsync(id);
        }
        
        public void UpdateAcademy(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj) {
            base.Channel.UpdateAcademy(academyObj);
        }
        
        public System.Threading.Tasks.Task UpdateAcademyAsync(CodeTechnologiesMVCADO.CodeTechWCF.AcademyModel academyObj) {
            return base.Channel.UpdateAcademyAsync(academyObj);
        }
        
        public void DeleteAcademy(int id) {
            base.Channel.DeleteAcademy(id);
        }
        
        public System.Threading.Tasks.Task DeleteAcademyAsync(int id) {
            return base.Channel.DeleteAcademyAsync(id);
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate> GetAllPrometricCandidates() {
            return base.Channel.GetAllPrometricCandidates();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate>> GetAllPrometricCandidatesAsync() {
            return base.Channel.GetAllPrometricCandidatesAsync();
        }
        
        public void BulkUploadPrometricCandidates(CodeTechnologiesMVCADO.CodeTechWCF.FileData inputexcel) {
            base.Channel.BulkUploadPrometricCandidates(inputexcel);
        }
        
        public System.Threading.Tasks.Task BulkUploadPrometricCandidatesAsync(CodeTechnologiesMVCADO.CodeTechWCF.FileData inputexcel) {
            return base.Channel.BulkUploadPrometricCandidatesAsync(inputexcel);
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Prometric> GetAllPrometrics() {
            return base.Channel.GetAllPrometrics();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Prometric>> GetAllPrometricsAsync() {
            return base.Channel.GetAllPrometricsAsync();
        }
        
        public void AddPrometric(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj) {
            base.Channel.AddPrometric(pObj);
        }
        
        public System.Threading.Tasks.Task AddPrometricAsync(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj) {
            return base.Channel.AddPrometricAsync(pObj);
        }
        
        public CodeTechnologiesMVCADO.CodeTechWCF.Prometric getPrometric(int id) {
            return base.Channel.getPrometric(id);
        }
        
        public System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.Prometric> getPrometricAsync(int id) {
            return base.Channel.getPrometricAsync(id);
        }
        
        public void UpdatePrometric(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj) {
            base.Channel.UpdatePrometric(pObj);
        }
        
        public System.Threading.Tasks.Task UpdatePrometricAsync(CodeTechnologiesMVCADO.CodeTechWCF.Prometric pObj) {
            return base.Channel.UpdatePrometricAsync(pObj);
        }
        
        public void DeletePrometric(int id) {
            base.Channel.DeletePrometric(id);
        }
        
        public System.Threading.Tasks.Task DeletePrometricAsync(int id) {
            return base.Channel.DeletePrometricAsync(id);
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions> getAllPrometricPromotions() {
            return base.Channel.getAllPrometricPromotions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions>> getAllPrometricPromotionsAsync() {
            return base.Channel.getAllPrometricPromotionsAsync();
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions> getPrometricPromotionWithSiteId(System.Nullable<int> id) {
            return base.Channel.getPrometricPromotionWithSiteId(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions>> getPrometricPromotionWithSiteIdAsync(System.Nullable<int> id) {
            return base.Channel.getPrometricPromotionWithSiteIdAsync(id);
        }
        
        public void AddPrometricPromotion(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj) {
            base.Channel.AddPrometricPromotion(ppObj);
        }
        
        public System.Threading.Tasks.Task AddPrometricPromotionAsync(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj) {
            return base.Channel.AddPrometricPromotionAsync(ppObj);
        }
        
        public CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions getPrometricPromotion(int id) {
            return base.Channel.getPrometricPromotion(id);
        }
        
        public System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions> getPrometricPromotionAsync(int id) {
            return base.Channel.getPrometricPromotionAsync(id);
        }
        
        public void UpdatePrometricPromotion(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj) {
            base.Channel.UpdatePrometricPromotion(ppObj);
        }
        
        public System.Threading.Tasks.Task UpdatePrometricPromotionAsync(CodeTechnologiesMVCADO.CodeTechWCF.PrometricPromotions ppObj) {
            return base.Channel.UpdatePrometricPromotionAsync(ppObj);
        }
        
        public void DeletePrometricPromotion(int id) {
            base.Channel.DeletePrometricPromotion(id);
        }
        
        public System.Threading.Tasks.Task DeletePrometricPromotionAsync(int id) {
            return base.Channel.DeletePrometricPromotionAsync(id);
        }
        
        public System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Institute> GetAllInstitutes() {
            return base.Channel.GetAllInstitutes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CodeTechnologiesMVCADO.CodeTechWCF.Institute>> GetAllInstitutesAsync() {
            return base.Channel.GetAllInstitutesAsync();
        }
        
        public void AddInstitute(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj) {
            base.Channel.AddInstitute(instiObj);
        }
        
        public System.Threading.Tasks.Task AddInstituteAsync(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj) {
            return base.Channel.AddInstituteAsync(instiObj);
        }
        
        public CodeTechnologiesMVCADO.CodeTechWCF.Institute getInstitute(int id) {
            return base.Channel.getInstitute(id);
        }
        
        public System.Threading.Tasks.Task<CodeTechnologiesMVCADO.CodeTechWCF.Institute> getInstituteAsync(int id) {
            return base.Channel.getInstituteAsync(id);
        }
        
        public void UpdateInstitute(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj) {
            base.Channel.UpdateInstitute(instiObj);
        }
        
        public System.Threading.Tasks.Task UpdateInstituteAsync(CodeTechnologiesMVCADO.CodeTechWCF.Institute instiObj) {
            return base.Channel.UpdateInstituteAsync(instiObj);
        }
        
        public void DeleteInstitute(int id) {
            base.Channel.DeleteInstitute(id);
        }
        
        public System.Threading.Tasks.Task DeleteInstituteAsync(int id) {
            return base.Channel.DeleteInstituteAsync(id);
        }
    }
}
